import type { Genre, GenreTheme } from "./types";

export const GENRES: Genre[] = [
  // ── Pop ──────────────────────────────────────────────────────────────────
  {
    id: "pop",
    name: "Pop",
    emoji: "💿",
    group: "Pop",
    searchTerms: [
      "The Beatles",
      "The Beach Boys",
      "ABBA",
      "Michael Jackson",
      "Prince",
      "Madonna",
      "David Bowie",
      "Fleetwood Mac",
      "U2",
      "Tears for Fears",
      "Crowded House",
      "10cc",
      "Todd Rundgren",
      "Squeeze",
      "XTC",
      "Prefab Sprout",
      "Aztec Camera",
      "Teenage Fanclub",
      "Fountains of Wayne",
      "Aimee Mann",
    ],
  },
  {
    id: "brit-pop",
    name: "Brit Pop",
    emoji: "🎡",
    group: "Pop",
    searchTerms: [
      "Oasis",
      "Blur",
      "Pulp",
      "Suede",
      "Elastica",
      "Sleeper",
      "Supergrass",
      "Ash",
      "Shed Seven",
      "Cast",
      "Longpigs",
      "Menswear",
      "Gene",
      "Dodgy",
      "Echobelly",
      "Mansun",
      "Catatonia",
      "Embrace",
      "Stereophonics",
      "Feeder",
    ],
  },
  {
    id: "kpop",
    name: "K-Pop",
    emoji: "🌸",
    group: "Pop",
    searchTerms: [
      "BTS",
      "Blackpink",
      "EXO",
      "SHINee",
      "Girls' Generation",
      "2NE1",
      "Big Bang",
      "Wonder Girls",
      "Monsta X",
      "Stray Kids",
      "TWICE",
      "aespa",
      "Red Velvet",
      "IU",
      "Taeyang",
      "Dean",
      "Zico",
      "Epik High",
      "f(x)",
      "BoA",
    ],
  },
  // ── Rock ─────────────────────────────────────────────────────────────────
  {
    id: "rock",
    name: "Rock",
    emoji: "🎸",
    group: "Rock",
    searchTerms: [
      "The Rolling Stones",
      "Led Zeppelin",
      "The Who",
      "Jimi Hendrix",
      "Cream",
      "The Doors",
      "Creedence Clearwater Revival",
      "Lynyrd Skynyrd",
      "Allman Brothers Band",
      "Free",
      "Little Feat",
      "Tom Petty & The Heartbreakers",
      "Bruce Springsteen",
      "Bob Seger",
      "John Mellencamp",
      "Georgia Satellites",
      "The Black Crowes",
      "The White Stripes",
      "Rival Sons",
      "Blackberry Smoke",
    ],
  },
  {
    id: "hard-rock",
    name: "Hard Rock",
    emoji: "🔊",
    group: "Rock",
    searchTerms: [
      "Deep Purple",
      "AC/DC",
      "Aerosmith",
      "Van Halen",
      "Thin Lizzy",
      "Bad Company",
      "UFO",
      "Montrose",
      "Rainbow",
      "Whitesnake",
      "Blue Öyster Cult",
      "Budgie",
      "Nazareth",
      "Accept",
      "Michael Schenker Group",
      "Y&T",
      "Kix",
      "Warrant",
      "Ratt",
      "Riot",
    ],
  },
  {
    id: "stoner-rock",
    name: "Stoner Rock",
    emoji: "🌋",
    group: "Rock",
    searchTerms: [
      "Sleep",
      "Electric Wizard",
      "Kyuss",
      "Fu Manchu",
      "Monster Magnet",
      "Brant Bjork",
      "Causa Sui",
      "Colour Haze",
      "Yob",
      "Earthless",
      "Wo Fat",
      "Truckfighters",
      "Lowrider",
      "Dozer",
      "Sungrazer",
      "Kamchatka",
      "Graveyard",
      "Witchcraft",
      "Blues Pills",
      "Monolord",
    ],
  },
  {
    id: "post-rock",
    name: "Post Rock",
    emoji: "🌌",
    group: "Rock",
    searchTerms: [
      "Godspeed You! Black Emperor",
      "Mogwai",
      "Explosions in the Sky",
      "Sigur Rós",
      "Tortoise",
      "Talk Talk",
      "Slint",
      "Bark Psychosis",
      "Labradford",
      "Stars of the Lid",
      "Do Make Say Think",
      "Dirty Three",
      "Calexico",
      "Bedhead",
      "American Football",
      "Rodan",
      "June of 44",
      "Spokane",
      "Tristeza",
      "Loscil",
    ],
  },
  // ── Metal ────────────────────────────────────────────────────────────────
  {
    id: "metal",
    name: "Metal",
    emoji: "⚔️",
    group: "Metal",
    searchTerms: [
      "Black Sabbath",
      "Iron Maiden",
      "Judas Priest",
      "Dio",
      "Rainbow",
      "Saxon",
      "Mercyful Fate",
      "Ozzy Osbourne",
      "Blue Öyster Cult",
      "Scorpions",
      "Wishbone Ash",
      "Cirith Ungol",
      "Manilla Road",
      "Candlemass",
      "Manowar",
      "Queensrÿche",
      "Fates Warning",
      "Pentagram",
      "Saint Vitus",
      "Trouble",
    ],
  },
  {
    id: "trash-metal",
    name: "Thrash Metal",
    emoji: "💀",
    group: "Metal",
    searchTerms: [
      "Metallica",
      "Slayer",
      "Megadeth",
      "Anthrax",
      "Testament",
      "Exodus",
      "Overkill",
      "Kreator",
      "Sodom",
      "Destruction",
      "Coroner",
      "Voivod",
      "Artillery",
      "Forbidden",
      "Vektor",
      "Havok",
      "Toxic Holocaust",
      "Sadus",
      "Heathen",
      "Violator",
    ],
  },
  {
    id: "death-metal",
    name: "Death Metal",
    emoji: "🦴",
    group: "Metal",
    searchTerms: [
      "Death",
      "Morbid Angel",
      "Obituary",
      "Cannibal Corpse",
      "Autopsy",
      "Possessed",
      "Dismember",
      "Entombed",
      "Bolt Thrower",
      "Immolation",
      "Incantation",
      "Suffocation",
      "Atheist",
      "Cynic",
      "Gorguts",
      "Demilich",
      "Necrophagist",
      "Nile",
      "Portal",
      "Ulcerate",
    ],
  },
  {
    id: "black-metal",
    name: "Black Metal",
    emoji: "🌑",
    group: "Metal",
    searchTerms: [
      "Bathory",
      "Mayhem",
      "Darkthrone",
      "Emperor",
      "Immortal",
      "Dissection",
      "Gorgoroth",
      "Marduk",
      "Satyricon",
      "Enslaved",
      "Mgła",
      "Deathspell Omega",
      "Wolves in the Throne Room",
      "Watain",
      "Lunar Aurora",
      "Drudkh",
      "Burzum",
      "Ofermod",
      "Spite",
      "Blaze Bayley",
    ],
  },
  // ── Hip-Hop ───────────────────────────────────────────────────────────────
  {
    id: "rap",
    name: "Rap",
    emoji: "🎤",
    group: "Hip-Hop",
    searchTerms: [
      "Rakim",
      "Big L",
      "Nas",
      "Big Pun",
      "Notorious B.I.G.",
      "Jay-Z",
      "Eminem",
      "GZA",
      "Ghostface Killah",
      "Redman",
      "Method Man",
      "Royce da 5'9",
      "Kendrick Lamar",
      "Freddie Gibbs",
      "Conway the Machine",
      "Westside Gunn",
      "Billy Woods",
      "Ransom",
      "Armand Hammer",
      "Boldy James",
    ],
  },
  {
    id: "hiphop",
    name: "Hip-Hop",
    emoji: "🎧",
    group: "Hip-Hop",
    searchTerms: [
      "Public Enemy",
      "De La Soul",
      "A Tribe Called Quest",
      "Gang Starr",
      "Organized Konfusion",
      "Souls of Mischief",
      "Dilated Peoples",
      "Madlib",
      "MF DOOM",
      "J Dilla",
      "Little Brother",
      "Slum Village",
      "Clipse",
      "Injury Reserve",
      "JPEGMAFIA",
      "Danny Brown",
      "Open Mike Eagle",
      "Your Old Droog",
      "Dalek",
      "Antipop Consortium",
    ],
  },
  // ── Electronic ───────────────────────────────────────────────────────────
  {
    id: "electronic",
    name: "Electronic",
    emoji: "🖲️",
    group: "Electronic",
    searchTerms: [
      "Kraftwerk",
      "Brian Eno",
      "Aphex Twin",
      "Boards of Canada",
      "Autechre",
      "The Orb",
      "Burial",
      "Massive Attack",
      "Portishead",
      "Squarepusher",
      "Plaid",
      "Actress",
      "Andy Stott",
      "Objekt",
      "Surgeon",
      "Basic Channel",
      "Drexciya",
      "Rhythm & Sound",
      "Pole",
      "Wolfgang Voigt",
    ],
  },
  // ── Jazz ─────────────────────────────────────────────────────────────────
  {
    id: "jazz",
    name: "Jazz",
    emoji: "🎷",
    group: "Jazz",
    searchTerms: [
      "Miles Davis",
      "John Coltrane",
      "Thelonious Monk",
      "Bill Evans",
      "Charles Mingus",
      "Ornette Coleman",
      "Eric Dolphy",
      "Herbie Hancock",
      "Wayne Shorter",
      "McCoy Tyner",
      "Lee Morgan",
      "Freddie Hubbard",
      "Andrew Hill",
      "Bobby Hutcherson",
      "Joe Henderson",
      "Woody Shaw",
      "Keith Jarrett",
      "Jan Garbarek",
      "Tomasz Stańko",
      "Esbjörn Svensson Trio",
    ],
  },
  // ── Soul / R&B / Funk ────────────────────────────────────────────────────
  {
    id: "rnb",
    name: "R&B",
    emoji: "🕯️",
    group: "Soul",
    searchTerms: [
      "Sam Cooke",
      "Otis Redding",
      "Al Green",
      "Curtis Mayfield",
      "Bill Withers",
      "Donny Hathaway",
      "Sade",
      "D'Angelo",
      "Maxwell",
      "Erykah Badu",
      "Raphael Saadiq",
      "Jill Scott",
      "Anthony Hamilton",
      "Musiq Soulchild",
      "Robert Glasper",
      "Frank Ocean",
      "Snoh Aalegra",
      "Ari Lennox",
      "Masego",
      "Hiatus Kaiyote",
    ],
  },
  {
    id: "funk",
    name: "Funk & Soul",
    emoji: "🕺",
    group: "Soul",
    searchTerms: [
      "James Brown",
      "Parliament-Funkadelic",
      "Sly & The Family Stone",
      "Meters",
      "Ohio Players",
      "Kool & The Gang",
      "Tower of Power",
      "Maceo Parker",
      "Fred Wesley",
      "Bootsy Collins",
      "Cymande",
      "Mandrill",
      "Roy Ayers",
      "Headhunters",
      "Average White Band",
      "Slave",
      "Bar-Kays",
      "Brick",
      "Fatback Band",
      "Zapp",
    ],
  },
  // ── Blues ─────────────────────────────────────────────────────────────────
  {
    id: "blues",
    name: "Blues",
    emoji: "🎺",
    group: "Blues",
    searchTerms: [
      "Robert Johnson",
      "Muddy Waters",
      "Howlin' Wolf",
      "Sonny Boy Williamson",
      "Little Walter",
      "Jimmy Reed",
      "Elmore James",
      "Freddie King",
      "Albert King",
      "B.B. King",
      "Buddy Guy",
      "Junior Wells",
      "Magic Sam",
      "Otis Rush",
      "J.B. Lenoir",
      "R.L. Burnside",
      "Junior Kimbrough",
      "T-Model Ford",
      "John Lee Hooker",
      "Son House",
    ],
  },
  // ── Folk / Country ───────────────────────────────────────────────────────
  {
    id: "folk",
    name: "Folk",
    emoji: "🪕",
    group: "Folk",
    searchTerms: [
      "Woody Guthrie",
      "Pete Seeger",
      "Lead Belly",
      "Bob Dylan",
      "Joan Baez",
      "Tim Buckley",
      "Nick Drake",
      "Bert Jansch",
      "John Renbourn",
      "Fairport Convention",
      "Pentangle",
      "Richard Thompson",
      "Sandy Denny",
      "John Martyn",
      "Fred Neil",
      "Tim Hardin",
      "Townes Van Zandt",
      "Michael Hurley",
      "Gillian Welch",
      "Iron & Wine",
    ],
  },
  {
    id: "country",
    name: "Country",
    emoji: "🤠",
    group: "Folk",
    searchTerms: [
      "Hank Williams",
      "Merle Haggard",
      "Waylon Jennings",
      "Willie Nelson",
      "Johnny Cash",
      "Townes Van Zandt",
      "Guy Clark",
      "Gram Parsons",
      "Flying Burrito Brothers",
      "Steve Earle",
      "Emmylou Harris",
      "John Prine",
      "Iris DeMent",
      "Gillian Welch",
      "Jason Isbell",
      "Sturgill Simpson",
      "Tyler Childers",
      "Colter Wall",
      "Charley Crockett",
      "Mdou Moctar",
    ],
  },
  // ── Punk ─────────────────────────────────────────────────────────────────
  {
    id: "punk",
    name: "Punk",
    emoji: "📍",
    group: "Punk",
    searchTerms: [
      "Sex Pistols",
      "The Clash",
      "Ramones",
      "Wire",
      "Gang of Four",
      "The Fall",
      "Buzzcocks",
      "X-Ray Spex",
      "Television",
      "Richard Hell & The Voidoids",
      "The Damned",
      "Stiff Little Fingers",
      "Dead Kennedys",
      "X",
      "Wipers",
      "Flipper",
      "Crime",
      "Kleenex",
      "Sham 69",
      "The Adverts",
    ],
  },
  {
    id: "hardcore-punk",
    name: "Hardcore",
    emoji: "⚡",
    group: "Punk",
    searchTerms: [
      "Black Flag",
      "Minor Threat",
      "Bad Brains",
      "Circle Jerks",
      "Dead Kennedys",
      "Discharge",
      "Negative Approach",
      "Void",
      "Adolescents",
      "Fear",
      "Descendents",
      "7 Seconds",
      "Youth of Today",
      "Agnostic Front",
      "Cro-Mags",
      "Poison Idea",
      "Siege",
      "Integrity",
      "Converge",
      "His Hero Is Gone",
    ],
  },
  // ── Reggae ───────────────────────────────────────────────────────────────
  {
    id: "reggae",
    name: "Reggae",
    emoji: "🌴",
    group: "Reggae",
    searchTerms: [
      "Bob Marley",
      "Peter Tosh",
      "Burning Spear",
      "Lee Scratch Perry",
      "Augustus Pablo",
      "King Tubby",
      "Horace Andy",
      "Gregory Isaacs",
      "Dennis Brown",
      "Culture",
      "The Abyssinians",
      "Steel Pulse",
      "Linton Kwesi Johnson",
      "Black Uhuru",
      "Sizzla",
      "Luciano",
      "Capleton",
      "Junior Murvin",
      "Max Romeo",
      "The Congos",
    ],
  },
  {
    id: "dub",
    name: "Dub",
    emoji: "〰️",
    group: "Reggae",
    searchTerms: [
      "King Tubby",
      "Lee Scratch Perry",
      "Augustus Pablo",
      "Scientist",
      "Prince Jammy",
      "Yabby You",
      "Joe Gibbs",
      "Mikey Dread",
      "Rhythm & Sound",
      "The Orb",
      "Pole",
      "Twilight Circus",
      "Mark Ernestus",
      "Burial",
      "Digital Mystikz",
      "Mala",
      "Coki",
      "Loefah",
      "Pinch",
      "Shackleton",
    ],
  },
  // ── Classical ────────────────────────────────────────────────────────────
  {
    id: "classical",
    name: "Classical",
    emoji: "🎻",
    group: "Classical",
    searchTerms: [
      "Johann Sebastian Bach",
      "Ludwig van Beethoven",
      "Wolfgang Amadeus Mozart",
      "Franz Schubert",
      "Johannes Brahms",
      "Gustav Mahler",
      "Anton Bruckner",
      "Dmitri Shostakovich",
      "Béla Bartók",
      "Igor Stravinsky",
      "Claude Debussy",
      "Maurice Ravel",
      "Arnold Schoenberg",
      "Alban Berg",
      "Anton Webern",
      "Olivier Messiaen",
      "György Ligeti",
      "Arvo Pärt",
      "Morton Feldman",
      "Helmut Lachenmann",
    ],
  },
];

// ─── Temi visivi ──────────────────────────────────────────────────────────────

export const GENRE_THEMES: Record<string, GenreTheme> = {
  // Pop
  pop: {
    accent: "#ff6eb4",
    accentGlow: "#ff6eb440",
    bg: "#130008",
    bgSurface: "#1e000f",
  },
  "brit-pop": {
    accent: "#e8c84a",
    accentGlow: "#e8c84a40",
    bg: "#100e00",
    bgSurface: "#1a1800",
  },
  kpop: {
    accent: "#ff85c8",
    accentGlow: "#ff85c840",
    bg: "#130010",
    bgSurface: "#200018",
  },
  // Rock
  rock: {
    accent: "#ff4500",
    accentGlow: "#ff450040",
    bg: "#130200",
    bgSurface: "#1e0500",
  },
  "hard-rock": {
    accent: "#ff6a00",
    accentGlow: "#ff6a0040",
    bg: "#110200",
    bgSurface: "#1c0400",
  },
  "stoner-rock": {
    accent: "#a8c400",
    accentGlow: "#a8c40040",
    bg: "#080c00",
    bgSurface: "#111500",
  },
  "post-rock": {
    accent: "#7eb8d4",
    accentGlow: "#7eb8d440",
    bg: "#020c10",
    bgSurface: "#04141c",
  },
  // Metal
  metal: {
    accent: "#cccccc",
    accentGlow: "#cccccc40",
    bg: "#080808",
    bgSurface: "#121212",
  },
  "trash-metal": {
    accent: "#ff2200",
    accentGlow: "#ff220040",
    bg: "#100000",
    bgSurface: "#1a0000",
  },
  "death-metal": {
    accent: "#8b0000",
    accentGlow: "#8b000060",
    bg: "#0a0000",
    bgSurface: "#120000",
  },
  "black-metal": {
    accent: "#4a4a6a",
    accentGlow: "#4a4a6a50",
    bg: "#030308",
    bgSurface: "#07070f",
  },
  // Hip-Hop
  rap: {
    accent: "#ffd700",
    accentGlow: "#ffd70040",
    bg: "#0f0d00",
    bgSurface: "#1a1500",
  },
  hiphop: {
    accent: "#ff8c00",
    accentGlow: "#ff8c0040",
    bg: "#0f0700",
    bgSurface: "#1a0e00",
  },
  // Electronic
  electronic: {
    accent: "#00ffcc",
    accentGlow: "#00ffcc40",
    bg: "#00100d",
    bgSurface: "#001a15",
  },
  dub: {
    accent: "#2de89a",
    accentGlow: "#2de89a40",
    bg: "#001209",
    bgSurface: "#001e10",
  },
  // Jazz
  jazz: {
    accent: "#c8a96e",
    accentGlow: "#c8a96e40",
    bg: "#0d0900",
    bgSurface: "#1a1200",
  },
  // Soul
  rnb: {
    accent: "#b06aff",
    accentGlow: "#b06aff40",
    bg: "#0d0020",
    bgSurface: "#160030",
  },
  funk: {
    accent: "#ff9a3c",
    accentGlow: "#ff9a3c40",
    bg: "#100600",
    bgSurface: "#1a0e00",
  },
  // Blues
  blues: {
    accent: "#4488ff",
    accentGlow: "#4488ff40",
    bg: "#000820",
    bgSurface: "#000f30",
  },
  // Folk
  folk: {
    accent: "#c8a26a",
    accentGlow: "#c8a26a40",
    bg: "#0d0800",
    bgSurface: "#181200",
  },
  country: {
    accent: "#d4a843",
    accentGlow: "#d4a84340",
    bg: "#0d0800",
    bgSurface: "#1a1200",
  },
  // Punk
  punk: {
    accent: "#ff1493",
    accentGlow: "#ff149340",
    bg: "#130010",
    bgSurface: "#1e0018",
  },
  "hardcore-punk": {
    accent: "#ff3300",
    accentGlow: "#ff330040",
    bg: "#100100",
    bgSurface: "#190200",
  },
  // Reggae
  reggae: {
    accent: "#44cc44",
    accentGlow: "#44cc4440",
    bg: "#020d02",
    bgSurface: "#041504",
  },
  // Classical
  classical: {
    accent: "#e8d5b0",
    accentGlow: "#e8d5b040",
    bg: "#0d0c08",
    bgSurface: "#181610",
  },
};

export const DEFAULT_THEME: GenreTheme = {
  accent: "#e8ff47",
  accentGlow: "#e8ff4740",
  bg: "#0a0a0f",
  bgSurface: "#13131e",
};

// ─── Helper ───────────────────────────────────────────────────────────────────

export function getGenreById(id: string): Genre | undefined {
  return GENRES.find((g) => g.id === id);
}

export function getThemeForGenre(genreId: string | null): GenreTheme {
  if (!genreId) return DEFAULT_THEME;
  return GENRE_THEMES[genreId] ?? DEFAULT_THEME;
}

export function themeToCSSVars(theme: GenreTheme): React.CSSProperties {
  return {
    "--accent-primary": theme.accent,
    "--accent-glow": theme.accentGlow,
    "--bg-base": theme.bg,
    "--bg-surface": theme.bgSurface,
    "--bg-elevated": adjustBrightness(theme.bgSurface, 1.4),
  } as React.CSSProperties;
}

function adjustBrightness(hex: string, factor: number): string {
  const r = parseInt(hex.slice(1, 3), 16);
  const g = parseInt(hex.slice(3, 5), 16);
  const b = parseInt(hex.slice(5, 7), 16);
  const clamp = (v: number) => Math.min(255, Math.round(v * factor));
  return `rgb(${clamp(r)}, ${clamp(g)}, ${clamp(b)})`;
}
