import type { Genre, GenreTheme } from "./types";

export const GENRES: Genre[] = [
  // ── Pop ──────────────────────────────────────────────────────────────────
  {
    id: "pop",
    name: "Pop",
    emoji: "✨",
    group: "Pop",
    searchTerms: [
      "The Beatles",
      "The Beach Boys",
      "ABBA",
      "Michael Jackson",
      "Prince",
      "Madonna",
      "Kate Bush",
      "David Bowie",
      "Fleetwood Mac",
      "Crowded House",
      "XTC",
      "Prefab Sprout",
      "Aztec Camera",
      "Squeeze",
      "Todd Rundgren",
      "Aimee Mann",
      "Fountains of Wayne",
      "Teenage Fanclub",
      "10cc",
      "Scritti Politti",
      "Robyn",
      "St. Vincent",
      "Carly Rae Jepsen",
      "Solange",
      "Janelle Monáe",
      "Björk",
      "Rufus Wainwright",
      "Feist",
      "Jenny Lewis",
      "Haim",
    ],
  },
  {
    id: "brit-pop",
    name: "Brit Pop",
    emoji: "🇬🇧",
    group: "Pop",
    searchTerms: [
      "Oasis",
      "Blur",
      "Pulp",
      "Suede",
      "Elastica",
      "The Verve",
      "Supergrass",
      "Ash",
      "Travis",
      "Sleeper",
      "Shed Seven",
      "Cast",
      "Catatonia",
      "Mansun",
      "Echobelly",
      "Gene",
      "Embrace",
      "Stereophonics",
      "Longpigs",
      "Marion",
      "Kula Shaker",
      "Space",
      "Northern Uproar",
      "Placebo",
      // "Powder", // no iTunes preview
      // "Salad", // no iTunes preview
      // "Thurman", // no iTunes preview
      "Menswear",
      "Geneva",
      // "Warm Jets", // no iTunes preview
    ],
  },
  {
    id: "kpop",
    name: "K-Pop",
    emoji: "🌸",
    group: "Pop",
    searchTerms: [
      "BTS",
      "Blackpink",
      "NewJeans",
      "aespa",
      "ITZY",
      "NCT 127",
      "EXO",
      "SHINee",
      "Girls' Generation",
      "2NE1",
      "Big Bang",
      "Red Velvet",
      "TWICE",
      "Stray Kids",
      "IU",
      "Epik High",
      "Taeyang",
      "Dean",
      "Zico",
      "BoA",
      "MAMAMOO",
      "BLACKSWAN",
      "Weeekly",
      "OH MY GIRL",
      "Dreamcatcher",
      "GFRIEND",
      "AOA",
      "SISTAR",
      "f(x)",
      "Wonder Girls",
      "Monsta X",
      "VIXX",
    ],
  },
  {
    id: "indie-pop",
    name: "Indie Pop",
    emoji: "🌼",
    group: "Pop",
    searchTerms: [
      "Belle & Sebastian",
      "Camera Obscura",
      "Alvvays",
      "Beach House",
      "Wild Nothing",
      "Real Estate",
      "The Pains of Being Pure at Heart",
      "Frankie Cosmos",
      "Vampire Weekend",
      "Phoenix",
      "Two Door Cinema Club",
      "Allo Darlin'",
      "The Clientele",
      "Trembling Blue Stars",
      "Saint Etienne",
      "The Field Mice",
      "Heavenly",
      "Tiger Trap",
      "The Softies",
      "Talulah Gosh",
      "The Magnetic Fields",
      "Broadcast",
      "Tullycraft",
      "Tender Trap",
      "Club 8",
      "Cats on Fire",
      "Literature",
      "The Courtneys",
      "Veronica Falls",
      "Standard Fare",
    ],
  },
  // ── Rock ─────────────────────────────────────────────────────────────────
  {
    id: "rock",
    name: "Rock",
    emoji: "🎸",
    group: "Rock",
    searchTerms: [
      "The Rolling Stones",
      "Led Zeppelin",
      "The Who",
      "Jimi Hendrix",
      "The Doors",
      "Creedence Clearwater Revival",
      "Lynyrd Skynyrd",
      "Tom Petty & The Heartbreakers",
      "Bruce Springsteen",
      "Allman Brothers Band",
      "Little Feat",
      "Free",
      "The White Stripes",
      "The Black Keys",
      "The Black Crowes",
      "Rival Sons",
      "Blackberry Smoke",
      "Drive-By Truckers",
      "Bad Company",
      "Rory Gallagher",
      "Robin Trower",
      "Mountain",
      "Humble Pie",
      "Foghat",
      "Status Quo",
      "Uriah Heep",
      "Bob Seger",
      "John Mellencamp",
      "Georgia Satellites",
      "Grand Funk Railroad",
    ],
  },
  {
    id: "grunge",
    name: "Grunge",
    emoji: "🌧️",
    group: "Rock",
    searchTerms: [
      "Nirvana",
      "Soundgarden",
      "Alice in Chains",
      "Pearl Jam",
      "Mudhoney",
      "Screaming Trees",
      "Melvins",
      "Green River",
      "Skin Yard",
      "Tad",
      "L7",
      "Babes in Toyland",
      "Hole",
      "Seaweed",
      "Hammerbox",
      "Malfunkshun",
      "Mother Love Bone",
      "Temple of the Dog",
      "Mad Season",
      "Candlebox",
      "7 Year Bitch",
      "Gruntruck",
      "Truly",
      "Brad",
      // "Flop", // no iTunes preview
      "Gas Huffer",
      "My Sister's Machine",
      // "Goodness", // no iTunes preview
      "Paw",
      // "Inflatable Soule", // no iTunes preview
    ],
  },
  {
    id: "psychedelic",
    name: "Psychedelic Rock",
    emoji: "🌀",
    group: "Rock",
    searchTerms: [
      "Pink Floyd",
      "13th Floor Elevators",
      "Spacemen 3",
      "Spiritualized",
      "The Velvet Underground",
      "Jefferson Airplane",
      "The Byrds",
      "Love",
      "Captain Beefheart",
      "Syd Barrett",
      "Soft Machine",
      "Hawkwind",
      "Can",
      "Neu!",
      "Amon Düül II",
      "Flaming Lips",
      "Tame Impala",
      "Brian Jonestown Massacre",
      "Wooden Shjips",
      "Goat",
      "Quicksilver Messenger Service",
      "Country Joe and the Fish",
      "The Pretty Things",
      // "United States of America", // no iTunes preview
      "Electric Prunes",
      "Silver Apples",
      "Os Mutantes",
      "Ty Segall",
      "Foxygen",
      "The Black Angels",
    ],
  },
  // {
  //   id: "noise-rock",
  //   name: "Noise Rock",
  //   emoji: "📢",
  //   group: "Rock",
  //   searchTerms: [
  //     // "Sonic Youth", // no iTunes preview (DGC/Universal rights dispute)
  //     "Swans",
  //     // "Big Black", // no iTunes preview
  //     "The Jesus Lizard",
  //     "Shellac",
  //     "Butthole Surfers",
  //     "Scratch Acid",
  //     "Unsane",
  //     "Today Is the Day",
  //     "Daughters",
  //     "Lightning Bolt",
  //     "Wolf Eyes",
  //     "Oxbow",
  //     // "Die Kreuzen", // no iTunes preview
  //     // "Killdozer", // no iTunes preview
  //     "Tar",
  //     // "Dazzling Killmen", // no iTunes preview
  //     // "Rapeman", // no iTunes preview
  //     // "Halo of Flies", // no iTunes preview
  //     // "Cows", // no iTunes preview
  //     // "Surgery", // no iTunes preview
  //     // "Hammerhead", // no iTunes preview
  //     "Brainiac",
  //     // "Mule", // no iTunes preview
  //     // "U.S. Maple", // no iTunes preview
  //     // "Flying Luttenbachers", // no iTunes preview
  //     // "Guzzard", // no iTunes preview
  //     // "Whores", // renamed to Whores. on iTunes
  //     // "Clockcleaner", // no iTunes preview
  //     "Pissed Jeans",
  //     "Helmet",
  //     "Mudhoney",
  //     "Drive Like Jehu",
  //     "Chavez",
  //     "Metz",
  //     "Preoccupations",
  //     "Protomartyr",
  //     "Cloud Nothings",
  //     "Uranium Club",
  //     "Portrayal of Guilt",
  //     "Show Me the Body",
  //     "Whores.",
  //     "Nothing",
  //     "Trash Talk",
  //     "Health",
  //     "Deafheaven",
  //   ],
  // },
  {
    id: "alternative",
    name: "Alternative",
    emoji: "🔊",
    group: "Rock",
    searchTerms: [
      "Sonic Youth", // no iTunes preview (DGC/Universal rights dispute)
      "Swans",
      "Big Black", // no iTunes preview
      "The Jesus Lizard",
      "Shellac",
      "Butthole Surfers",
      "Scratch Acid",
      "Unsane",
      "Today Is the Day",
      "Daughters",
      "Lightning Bolt",
      "Wolf Eyes",
      "Oxbow",
      "Die Kreuzen", // no iTunes preview
      "Killdozer", // no iTunes preview
      "Tar",
      "Dazzling Killmen", // no iTunes preview
      "Rapeman", // no iTunes preview
      "Halo of Flies", // no iTunes preview
      "Cows", // no iTunes preview
      "Surgery", // no iTunes preview
      "Hammerhead", // no iTunes preview
      "Brainiac",
      "Mule", // no iTunes preview
      "U.S. Maple", // no iTunes preview
      "Flying Luttenbachers", // no iTunes preview
      "Guzzard", // no iTunes preview
      "Whores", // renamed to Whores. on iTunes
      "Clockcleaner", // no iTunes preview
      "Pissed Jeans",
      "Helmet",
      "Mudhoney",
      "Drive Like Jehu",
      "Chavez",
      "Metz",
      "Preoccupations",
      "Protomartyr",
      "Cloud Nothings",
      "Uranium Club",
      "Portrayal of Guilt",
      "Show Me the Body",
      "Whores.",
      "Nothing",
      "Trash Talk",
      "Health",
      "Deafheaven",
      "R.E.M.",
      "Pixies",
      "Pavement",
      "Guided By Voices",
      "Sebadoh",
      "Built to Spill",
      "Modest Mouse",
      "Wilco",
      "Smashing Pumpkins",
      "Weezer",
      "Liz Phair",
      "Superchunk",
      "Yo La Tengo",
      "Archers of Loaf",
      "Sleater-Kinney",
      "Belly",
      "Throwing Muses",
      "The Replacements",
      "Hüsker Dü",
      "The Minutemen",
      "Meat Puppets",
      "Mission of Burma",
      "Feelies",
      "Helium",
      "Dump",
      "Poster Children",
      "Velocity Girl",
      "Breeders",
      "Nada Surf",
      "Dinosaur Jr",
    ],
  },
  {
    id: "hard-rock",
    name: "Hard Rock",
    emoji: "🔥",
    group: "Rock",
    searchTerms: [
      "Deep Purple",
      "AC/DC",
      "Aerosmith",
      "Van Halen",
      "Thin Lizzy",
      "Motörhead",
      "Guns N' Roses",
      "Alice Cooper",
      "Bad Company",
      "UFO",
      "Rainbow",
      "Whitesnake",
      "Blue Öyster Cult",
      "Nazareth",
      "Humble Pie",
      "Uriah Heep",
      "Status Quo",
      "Montrose",
      "Riot",
      "Kix",
      "Dokken",
      "Ratt",
      "Winger",
      "Great White",
      "Michael Schenker Group",
      "Y&T",
      "Dirty Looks",
      "Keel",
      "Warrant",
      "Cinderella",
    ],
  },
  {
    id: "stoner-rock",
    name: "Stoner Rock",
    emoji: "🌿",
    group: "Rock",
    searchTerms: [
      "Sleep",
      "Electric Wizard",
      "Kyuss",
      "Fu Manchu",
      "Monster Magnet",
      "Brant Bjork",
      "Causa Sui",
      "Colour Haze",
      "Yob",
      "Earthless",
      "Truckfighters",
      "Graveyard",
      "Witchcraft",
      "Blues Pills",
      "Monolord",
      "Dozer",
      "Lowrider",
      "Kamchatka",
      "Wo Fat",
      "Sungrazer",
      "Bongripper",
      "Weedeater",
      "Bongzilla",
      "High on Fire",
      "Orange Goblin",
      "Acid King",
      "Ufomammut",
      "Windhand",
      "Elder",
      "Conan",
    ],
  },
  {
    id: "post-rock",
    name: "Post Rock",
    emoji: "🌌",
    group: "Rock",
    searchTerms: [
      "Godspeed You! Black Emperor",
      "Mogwai",
      "Explosions in the Sky",
      "Sigur Rós",
      "Tortoise",
      "Talk Talk",
      "Slint",
      "Bark Psychosis",
      "Stars of the Lid",
      "Do Make Say Think",
      "This Will Destroy You",
      "Caspian",
      "Hammock",
      "Dirty Three",
      "Labradford",
      "Bedhead",
      "Rodan",
      "Rachel's",
      "Jessamine",
      "Gastr del Sol",
      "Fly Pan Am",
      "A Silver Mt. Zion",
      "65daysofstatic",
      "pg.lost",
      "Mono",
      // "Main", // no iTunes preview
      "Seefeel",
      // "Pell Mell", // no iTunes preview
      // "Cul de Sac", // no iTunes preview
      "Loscil",
    ],
  },
  // ── Metal ────────────────────────────────────────────────────────────────
  {
    id: "metal",
    name: "Metal",
    emoji: "🤘",
    group: "Metal",
    searchTerms: [
      "Black Sabbath",
      "Iron Maiden",
      "Judas Priest",
      "Dio",
      "Ozzy Osbourne",
      "Saxon",
      "Mercyful Fate",
      "Candlemass",
      "Saint Vitus",
      "Pentagram",
      "Cirith Ungol",
      "Manilla Road",
      "Trouble",
      "Queensrÿche",
      "Fates Warning",
      "Manowar",
      "Angel Witch",
      "Tygers of Pan Tang",
      "Witchfinder General",
      "Venom",
      "Diamond Head",
      "Girlschool",
      "Raven",
      // "Sortilège", // no iTunes preview
      "Helloween",
      "Running Wild",
      "Accept",
      "Grave Digger",
      // "Omen", // no iTunes preview
      // "Liege Lord", // no iTunes preview
    ],
  },
  {
    id: "trash-metal",
    name: "Thrash Metal",
    emoji: "💀",
    group: "Metal",
    searchTerms: [
      "Metallica",
      "Slayer",
      "Megadeth",
      "Anthrax",
      "Testament",
      "Exodus",
      "Overkill",
      "Kreator",
      "Sodom",
      "Destruction",
      "Coroner",
      "Voivod",
      "Artillery",
      "Forbidden",
      "Vektor",
      "Havok",
      "Municipal Waste",
      "Sadus",
      "Heathen",
      "Toxic Holocaust",
      "Dark Angel",
      "Flotsam and Jetsam",
      "Nuclear Assault",
      "Whiplash",
      "Death Angel",
      // "Evildead", // no iTunes preview
      // "Num Skull", // no iTunes preview
      "Razor",
      "Atrophy",
      "Demolition Hammer",
    ],
  },
  {
    id: "death-metal",
    name: "Death Metal",
    emoji: "☠️",
    group: "Metal",
    searchTerms: [
      "Death",
      "Morbid Angel",
      "Obituary",
      "Cannibal Corpse",
      "Autopsy",
      "Possessed",
      "Dismember",
      "Entombed",
      "Bolt Thrower",
      "Immolation",
      "Incantation",
      "Suffocation",
      "Atheist",
      "Cynic",
      "Gorguts",
      "Demilich",
      "Necrophagist",
      "Nile",
      "Portal",
      "Ulcerate",
      "Vader",
      "Deicide",
      "Monstrosity",
      "Sinister",
      "Brutality",
      "Broken Hope",
      "Malevolent Creation",
      "Pestilence",
      "Asphyx",
      "Internment",
    ],
  },
  {
    id: "black-metal",
    name: "Black Metal",
    emoji: "🌑",
    group: "Metal",
    searchTerms: [
      "Bathory",
      "Venom",
      "Hellhammer",
      "Celtic Frost",
      "Enslaved",
      "Satyricon",
      "Agalloch",
      "Wolves in the Throne Room",
      "Watain",
      "Taake",
      "Darkthrone",
      "Mayhem",
      "Immortal",
      "Emperor",
      "Dissection",
      "Gorgoroth",
      "Marduk",
      "Drudkh",
      "Mgła",
      "Abbath",
      "Gaahl's Wyrd",
      "Liturgy",
      "Deafheaven",
      "Oranssi Pazuzu",
      "Ulver",
      "Alcest",
      "Lantlôs",
      "Lifelover",
      "Shining",
      "Spectral Wound",
      "Burzum", // Byelobog — Varg contro distribuzione digitale
      "Deathspell Omega", // Norma Evangelium Diaboli — volutamente offline
      "Funeral Mist", // Norma Evangelium Diaboli — volutamente offline
      "Horna", // Woodcut Records — rarissimo su iTunes
      "Sargeist", // Moribund/Woodcut — rarissimo su iTunes
      "Windir", // Head Not Found — rarissimo su iTunes
      "Clandestine Blaze", // Northern Heritage — volutamente offline
      "Mutiilation", // Les Légions Noires — volutamente offline
      "Abruptum", // DSP — non digitalizzato
      "Ofermod", // Paradigm Recordings — rarissimo
    ],
  },
  // ── Hip-Hop ───────────────────────────────────────────────────────────────
  {
    id: "rap",
    name: "Rap",
    emoji: "🎤",
    group: "Hip-Hop",
    searchTerms: [
      "Rakim",
      "Nas",
      "Jay-Z",
      "Notorious B.I.G.",
      "Big L",
      "Big Pun",
      "Eminem",
      "Scarface",
      "GZA",
      "Ghostface Killah",
      "Redman",
      "Method Man",
      "Kendrick Lamar",
      "Freddie Gibbs",
      "Conway the Machine",
      "Westside Gunn",
      "Billy Woods",
      "Boldy James",
      "Royce da 5'9",
      "Your Old Droog",
      "Big Daddy Kane",
      "Kool G Rap",
      "Ice Cube",
      "Wu-Tang Clan",
      "Mobb Deep",
      "DMX",
      "Cam'ron",
      "Jadakiss",
      "AZ",
      "Fabolous",
    ],
  },
  {
    id: "hiphop",
    name: "Hip-Hop",
    emoji: "🎧",
    group: "Hip-Hop",
    searchTerms: [
      "Public Enemy",
      "De La Soul",
      "A Tribe Called Quest",
      "Gang Starr",
      "Organized Konfusion",
      "Souls of Mischief",
      "Dilated Peoples",
      "Madlib",
      "MF DOOM",
      "J Dilla",
      "Little Brother",
      "Slum Village",
      "Clipse",
      "Aesop Rock",
      "Camp Lo",
      "JPEGMAFIA",
      "Danny Brown",
      "Open Mike Eagle",
      "Injury Reserve",
      "Black Star",
      "Digable Planets",
      "Hieroglyphics",
      "Quasimoto",
      "Talib Kweli",
      "Jurassic 5",
      "Blackalicious",
      "Atmosphere",
      "Brother Ali",
      "Dalek",
      "Antipop Consortium",
    ],
  },
  // ── Electronic ────────────────────────────────────────────────────────────
  // {
  //   id: "electronic",
  //   name: "Electronic",
  //   emoji: "🎛️",
  //   group: "Electronic",
  //   searchTerms: [
  //     "Squarepusher",
  //     "Plaid",
  //     "Clark",
  //     "Bibio",
  //     "Lone",
  //     "Drexciya",
  //     "Basic Channel",
  //     "Plastikman",
  //     "Jeff Mills",
  //     "Robert Hood",
  //     "Underground Resistance",
  //     "Model 500",
  //     "DJ Rolando",
  //     "Surgeon",
  //     "Claude Young",
  //     "Burial",
  //     "Andy Stott",
  //     "Actress",
  //     "Objekt",
  //     "Rhythm & Sound",
  //     "Pole",
  //     "Wolfgang Voigt",
  //     "Richie Hawtin",
  //     "Speedy J",
  //     "Dave Clarke",
  //     "Orbital",
  //     "Four Tet",
  //     "Larry Heard",
  //     "Frankie Knuckles",
  //     "Larry Levan",
  //     "Todd Terry",
  //     "Kraftwerk", // Kling Klang — cause legali attive
  //     "Daft Punk", // Columbia/Sony — catalogo in limbo post-scioglimento
  //     "Massive Attack", // Virgin/Universal — gap regionali
  //     "Portishead", // Island/Universal — coverage irregolare
  //     "Chemical Brothers", // Virgin/EMI — rischio gap
  //     "Underworld", // Junior Boy's Own — gap frequenti
  //     "The Prodigy", // XL — verificare coverage
  //     "The Orb", // Island/Big Life — rarissimo
  //   ],
  // },
  {
    id: "electro-ambient",
    name: "Electro / Ambient",
    emoji: "🌫️",
    group: "Electronic",
    searchTerms: [
       "Squarepusher",
      "Plaid",
      "Clark",
      "Bibio",
      "Lone",
      "Drexciya",
      "Basic Channel",
      "Plastikman",
      "Jeff Mills",
      "Robert Hood",
      "Underground Resistance",
      "Model 500",
      "DJ Rolando",
      "Surgeon",
      "Claude Young",
      "Burial",
      "Andy Stott",
      "Actress",
      "Objekt",
      "Rhythm & Sound",
      "Pole",
      "Wolfgang Voigt",
      "Richie Hawtin",
      "Speedy J",
      "Dave Clarke",
      "Orbital",
      "Four Tet",
      "Larry Heard",
      "Frankie Knuckles",
      "Larry Levan",
      "Todd Terry",
      "Kraftwerk", // Kling Klang — cause legali attive
      "Daft Punk", // Columbia/Sony — catalogo in limbo post-scioglimento
      "Massive Attack", // Virgin/Universal — gap regionali
      "Portishead", // Island/Universal — coverage irregolare
      "Chemical Brothers", // Virgin/EMI — rischio gap
      "Underworld", // Junior Boy's Own — gap frequenti
      "The Prodigy", // XL — verificare coverage
      "The Orb", // Island/Big Life — rarissimo
      "Aphex Twin",
      "Boards of Canada",
      "Autechre",
      "Stars of the Lid",
      "Grouper",
      "Eluvium",
      "Loscil",
      "Windy & Carl",
      "Tycho",
      "Com Truise",
      "Shigeto",
      "Dabrye",
      "Tim Hecker",
      "Fennesz",
      "Lawrence English",
      "Rafael Anton Irisarri",
      "Taylor Deupree",
      "Gas",
      "Monolake",
      "Alva Noto",
      "Ryoji Ikeda",
      "Pan Sonic",
      "Oval",
      "Nils Frahm",
      "Ólafur Arnalds",
      "Max Richter",
      "Deaf Center",
      "Ben Frost",
      "Jóhann Jóhannsson",
      "Hauschka",
      // "Brian Eno", // Virgin/EG/Universal — dispute storiche, coverage irregolare
      // "Tangerine Dream", // Virgin/Universal — catalogo frammentato
      // "Klaus Schulze", // Brain/Universal — rarissimo su iTunes
      // "Coil", // Threshold House — mai distribuiti digitalmente per scelta
      // "William Basinski", // 2062 — coverage molto scarsa
      // "Harold Budd", // EG/Land — rarissimo
      // "Biosphere", // Apollo/R&S — gap frequenti
      // "The Caretaker", // History Always Favours — non su iTunes
      // "Lustmord", // Side Effects — rarissimo
    ],
  },
  // ── Jazz ──────────────────────────────────────────────────────────────────
  {
    id: "jazz",
    name: "Jazz",
    emoji: "🎷",
    group: "Jazz",
    searchTerms: [
      "Miles Davis",
      "John Coltrane",
      "Thelonious Monk",
      "Bill Evans",
      "Charles Mingus",
      "Ornette Coleman",
      "Eric Dolphy",
      "Herbie Hancock",
      "Wayne Shorter",
      "McCoy Tyner",
      "Lee Morgan",
      "Freddie Hubbard",
      "Andrew Hill",
      "Bobby Hutcherson",
      "Joe Henderson",
      "Woody Shaw",
      "Keith Jarrett",
      "Jan Garbarek",
      "Tomasz Stańko",
      "Esbjörn Svensson Trio",
      "Art Blakey",
      "Clifford Brown",
      "Sonny Rollins",
      "Wes Montgomery",
      "Grant Green",
      "Kenny Dorham",
      "Hank Mobley",
      "Jimmy Smith",
      "Eddie Harris",
      "Don Cherry",
    ],
  },
  // ── Soul ──────────────────────────────────────────────────────────────────
  // {
  //   id: "rnb",
  //   name: "R&B",
  //   emoji: "💜",
  //   group: "Soul",
  //   searchTerms: [
  //     "Sam Cooke",
  //     "Otis Redding",
  //     "Al Green",
  //     "Curtis Mayfield",
  //     "Bill Withers",
  //     "Donny Hathaway",
  //     "Marvin Gaye",
  //     "Stevie Wonder",
  //     "Teddy Pendergrass",
  //     "Barry White",
  //     "Anita Baker",
  //     "Phyllis Hyman",
  //     "Chaka Khan",
  //     "Patti LaBelle",
  //     "Whitney Houston",
  //     "Luther Vandross",
  //     "Sade",
  //     "D'Angelo",
  //     "Maxwell",
  //     "Erykah Badu",
  //     "Raphael Saadiq",
  //     "Jill Scott",
  //     "Anthony Hamilton",
  //     "Musiq Soulchild",
  //     "Robert Glasper",
  //     "Frank Ocean",
  //     "Snoh Aalegra",
  //     "Ari Lennox",
  //     "Hiatus Kaiyote",
  //     "Masego",
  //   ],
  // },
  {
    id: "funk",
    name: "Funk & Soul",
    emoji: "🕺",
    group: "Soul",
    searchTerms: [
      "James Brown",
      "Parliament-Funkadelic",
      "Sly & The Family Stone",
      "The Meters",
      "Ohio Players",
      "Kool & The Gang",
      "Tower of Power",
      "Maceo Parker",
      "Fred Wesley",
      "Bootsy Collins",
      "Cymande",
      "Mandrill",
      "Roy Ayers",
      "Headhunters",
      "Average White Band",
      "Cameo",
      "Trouble Funk",
      "Bar-Kays",
      "Zapp",
      "Slave",
      "Betty Davis",
      "Rufus",
      // "Confunkshun", // no iTunes preview
      "Midnight Star",
      "Dazz Band",
      "Rick James",
      "Fatback Band",
      "Brass Construction",
      "Maze",
      "Con Funk Shun",
    ],
  },
  // {
  //   id: "disco",
  //   name: "Disco",
  //   emoji: "🪩",
  //   group: "Soul",
  //   searchTerms: [
  //     "Giorgio Moroder",
  //     "Donna Summer",
  //     "Chic",
  //     "Gloria Gaynor",
  //     "Sylvester",
  //     "Grace Jones",
  //     "Diana Ross",
  //     "Sister Sledge",
  //     "Shalamar",
  //     "Cerrone",
  //     "Patrick Cowley",
  //     "Salsoul Orchestra",
  //     "Loleatta Holloway",
  //     "Dan Hartman",
  //     "Thelma Houston",
  //     // "Musique", // no iTunes preview
  //     "First Choice",
  //     // "Ritchie Family", // no iTunes preview
  //     "Village People",
  //     "KC and the Sunshine Band",
  //     "Bee Gees",
  //     "Patrick Adams",
  //     "MFSB",
  //     "Instant Funk",
  //     "Brainstorm",
  //     // "Cloud One", // no iTunes preview
  //     // "D.C. LaRue", // no iTunes preview
  //     "Alicia Bridges",
  //     "Lime",
  //     // "Foxy", // no iTunes preview
  //   ],
  // },
  // {
  //   id: "motown",
  //   name: "Motown",
  //   emoji: "🎙️",
  //   group: "Soul",
  //   searchTerms: [
  //     "Marvin Gaye",
  //     "Stevie Wonder",
  //     "The Temptations",
  //     "The Four Tops",
  //     "Diana Ross & the Supremes",
  //     "Smokey Robinson",
  //     "Martha and the Vandellas",
  //     "Gladys Knight & the Pips",
  //     "The Isley Brothers",
  //     "Junior Walker & the All Stars",
  //     "The Miracles",
  //     "Lionel Richie",
  //     "Jackson 5",
  //     "Eddie Kendricks",
  //     "David Ruffin",
  //     "Marvelettes",
  //     "Mary Wells",
  //     "Tammi Terrell",
  //     "Kim Weston",
  //     "The Funk Brothers",
  //     "Velvelettes",
  //     "Contours",
  //     "Undisputed Truth",
  //     "Rare Earth",
  //     "Barrett Strong",
  //     "The Monitors",
  //     "The Elgins",
  //     "Edwin Starr",
  //     "Shorty Long",
  //     "The Originals",
  //   ],
  // },
  // {
  //   id: "gospel",
  //   name: "Gospel & Soul",
  //   emoji: "🙏",
  //   group: "Soul",
  //   searchTerms: [
  //     "Aretha Franklin",
  //     "Mahalia Jackson",
  //     "Sam Cooke",
  //     "Ray Charles",
  //     "Al Green",
  //     "Staple Singers",
  //     "Mavis Staples",
  //     "Blind Willie Johnson",
  //     "Sister Rosetta Tharpe",
  //     "Clara Ward",
  //     "James Cleveland",
  //     "Shirley Caesar",
  //     "Andraé Crouch",
  //     "Edwin Hawkins",
  //     "Kirk Franklin",
  //     "Yolanda Adams",
  //     "CeCe Winans",
  //     "BeBe Winans",
  //     "Tramaine Hawkins",
  //     "Walter Hawkins",
  //     "Soul Stirrers",
  //     "Five Blind Boys of Alabama",
  //     "Swan Silvertones",
  //     "Sensational Nightingales",
  //     "Thomas A. Dorsey",
  //     "Mississippi Mass Choir",
  //     "Hezekiah Walker",
  //     "Fred Hammond",
  //     "Donald Lawrence",
  //     "Richard Smallwood",
  //   ],
  // },
  {
    id: "afrobeat",
    name: "Afrobeat",
    emoji: "🥁",
    group: "Soul",
    searchTerms: [
      "Fela Kuti",
      "Tony Allen",
      "Antibalas",
      "Seun Kuti",
      "Femi Kuti",
      "Orlando Julius",
      "William Onyeabor",
      "Mulatu Astatke",
      "Miriam Makeba",
      "Hugh Masekela",
      "King Sunny Ade",
      "Ebenezer Obey",
      "Osibisa",
      "Ebo Taylor",
      "Pat Thomas",
      // "Gyedu-Blay Ambolley", // no iTunes preview
      // "Ifang Bondi", // no iTunes preview
      "Orchestra Baobab",
      "Youssou N'Dour",
      "Manu Dibango",
      "Francis Bebey",
      "Celestine Ukwu",
      "Hailu Mergia",
      // "Bembeya Jazz", // no iTunes preview
      // "Super Rail Band", // no iTunes preview
      "Oumou Sangaré",
      "Salif Keita",
      "Toumani Diabaté",
      "Ali Farka Touré",
      "Amadou & Mariam",
    ],
  },
  // {
  //   id: "latin",
  //   name: "Latin",
  //   emoji: "🌶️",
  //   group: "Soul",
  //   searchTerms: [
  //     "Celia Cruz",
  //     "Tito Puente",
  //     "Buena Vista Social Club",
  //     "Caetano Veloso",
  //     "Gilberto Gil",
  //     "João Gilberto",
  //     "Tom Jobim",
  //     "Astor Piazzolla",
  //     "Carlos Santana",
  //     "Ruben Blades",
  //     "Willie Colón",
  //     "Héctor Lavoe",
  //     "Eddie Palmieri",
  //     "Ibrahim Ferrer",
  //     "Compay Segundo",
  //     "Beny Moré",
  //     "Mongo Santamaría",
  //     "Ray Barretto",
  //     "Chucho Valdés",
  //     "Irakere",
  //     "Silvio Rodríguez",
  //     "Pablo Milanés",
  //     "Chico Buarque",
  //     "Elis Regina",
  //     "Carlos Gardel",
  //     "Mercedes Sosa",
  //     "Violeta Parra",
  //     "La Lupe",
  //     "Fania All Stars",
  //     // "Roberto Roena", // no iTunes preview
  //   ],
  // },
  // ── Blues ─────────────────────────────────────────────────────────────────
  {
    id: "blues",
    name: "Blues",
    emoji: "🎵",
    group: "Blues",
    searchTerms: [
      "Robert Johnson",
      "Muddy Waters",
      "Howlin' Wolf",
      "Sonny Boy Williamson",
      "Little Walter",
      "Jimmy Reed",
      "Elmore James",
      "Freddie King",
      "Albert King",
      "B.B. King",
      "Buddy Guy",
      "Junior Wells",
      "Magic Sam",
      "Otis Rush",
      "J.B. Lenoir",
      "R.L. Burnside",
      "Junior Kimbrough",
      "Son House",
      "John Lee Hooker",
      "T-Model Ford",
      "Lightnin' Hopkins",
      "Blind Lemon Jefferson",
      "Tampa Red",
      "Big Bill Broonzy",
      "Memphis Minnie",
      "Clarence 'Gatemouth' Brown",
      "Little Milton",
      "Albert Collins",
      "Johnny Winter",
      "Luther Allison",
    ],
  },
  // ── Folk ──────────────────────────────────────────────────────────────────
  {
    id: "folk",
    name: "Folk",
    emoji: "🪕",
    group: "Folk",
    searchTerms: [
      "Woody Guthrie",
      "Pete Seeger",
      "Lead Belly",
      "Bob Dylan",
      "Joan Baez",
      "Tim Buckley",
      "Nick Drake",
      "Bert Jansch",
      "John Renbourn",
      "Fairport Convention",
      "Pentangle",
      "Richard Thompson",
      "Sandy Denny",
      "John Martyn",
      "Fred Neil",
      "Tim Hardin",
      "Townes Van Zandt",
      "Michael Hurley",
      "Gillian Welch",
      "Iron & Wine",
      "Joni Mitchell",
      "Anne Briggs",
      "Shirley Collins",
      "Vashti Bunyan",
      "Karen Dalton",
      "Roy Harper",
      // "Jackson C. Frank", // no iTunes preview
      "Davey Graham",
      // "Nic Jones", // no iTunes preview
      "June Tabor",
    ],
  },
  {
    id: "country",
    name: "Country",
    emoji: "🤠",
    group: "Folk",
    searchTerms: [
      "Hank Williams",
      "Merle Haggard",
      "Waylon Jennings",
      "Willie Nelson",
      "Johnny Cash",
      "Townes Van Zandt",
      "Guy Clark",
      "Gram Parsons",
      "Flying Burrito Brothers",
      "Kris Kristofferson",
      "Emmylou Harris",
      "Steve Earle",
      "John Prine",
      "Iris DeMent",
      "Gillian Welch",
      "Jason Isbell",
      "Sturgill Simpson",
      "Tyler Childers",
      "Colter Wall",
      "Charley Crockett",
      "Buck Owens",
      "George Jones",
      "Loretta Lynn",
      "Tammy Wynette",
      "Dolly Parton",
      "Roger Miller",
      "Billy Joe Shaver",
      "David Allan Coe",
      "Bobby Bare",
      "Don Williams",
    ],
  },
  // ── Punk ──────────────────────────────────────────────────────────────────
  {
    id: "punk",
    name: "Punk",
    emoji: "🔱",
    group: "Punk",
    searchTerms: [
      "Sex Pistols",
      "The Clash",
      "Ramones",
      "Buzzcocks",
      "The Adverts",
      "Sham 69",
      "The Vibrators",
      "X-Ray Spex",
      "Television",
      "Richard Hell & The Voidoids",
      "The Damned",
      "The Stranglers",
      "Stiff Little Fingers",
      "Dead Kennedys",
      "X",
      "Wipers",
      "Flipper",
      "Crime",
      "Kleenex",
      "Penetration",
      "The Saints",
      "Radio Birdman",
      "The Undertones",
      "Subway Sect",
      "The Slits",
      "Essential Logic",
      "Raincoats",
      "Au Pairs",
      "Delta 5",
      "Crass",
    ],
  },
  {
    id: "hardcore-punk",
    name: "Hardcore",
    emoji: "⚡",
    group: "Punk",
    searchTerms: [
      "Black Flag",
      "Minor Threat",
      "Bad Brains",
      "Circle Jerks",
      "Dead Kennedys",
      "Discharge",
      "Negative Approach",
      "Void",
      "Adolescents",
      "Fear",
      "Descendents",
      "7 Seconds",
      "Youth of Today",
      "Agnostic Front",
      "Cro-Mags",
      "Poison Idea",
      "Siege",
      "Integrity",
      "Gorilla Biscuits",
      "Judge",
      "Chain of Strength",
      "Wide Awake",
      "Carry On",
      "Ten Yard Fight",
      "Misfits",
      "Antidote",
      "Reagan Youth",
      "Urban Waste",
      "Negative FX",
      "SS Decontrol",
    ],
  },
  {
    id: "post-hardcore",
    name: "Post-Hardcore",
    emoji: "⚡",
    group: "Punk",
    searchTerms: [
      "Fugazi",
      "Polvo",
      "Drive Like Jehu",
      "Jawbox",
      "Refused",
      "At the Drive-In",
      "Converge",
      "Botch",
      "His Hero Is Gone",
      "Pg. 99",
      "Nation of Ulysses",
      "Lungfish",
      "Shudder to Think",
      "Girls Against Boys",
      "Quicksand",
      "Chavez",
      "Bitch Magnet",
      "Seam",
      "Crain",
      "June of 44",
      "Unwound",
      "Born Against",
      // "Swiz", // no iTunes preview
      "Rites of Spring",
      "Hoover",
      "Soulside",
      "Embrace",
      // "Gray Matter", // no iTunes preview
      // "Three", // no iTunes preview
      "Bluetip",
    ],
  },
  {
    id: "emo",
    name: "Emo",
    emoji: "💔",
    group: "Punk",
    searchTerms: [
      "Sunny Day Real Estate",
      "Cap'n Jazz",
      "American Football",
      "The Promise Ring",
      // "Christie Front Drive", // no iTunes preview
      "Mineral",
      "Texas Is the Reason",
      "Braid",
      "Embrace",
      "Rites of Spring",
      // "Native Nod", // no iTunes preview
      // "Still Life", // no iTunes preview
      // "Boys Life", // no iTunes preview
      // "Kodan Armada", // no iTunes preview
      // "Portraits of Past", // no iTunes preview
      "I Hate Myself",
      "Saetia",
      "Envy",
      "Moss Icon",
      "Hoover",
      "Hot Water Music",
      "The Get Up Kids",
      "Thursday",
      "Brand New",
      "The Hotelier",
      "Pity Sex",
      "Touché Amoré",
      "La Dispute",
      "Jawbreaker",
      "Samiam",
    ],
  },
  // ── New Wave / Post-Punk ──────────────────────────────────────────────────
  {
    id: "post-punk",
    name: "Post-Punk",
    emoji: "🖤",
    group: "Punk",
    searchTerms: [
      "Joy Division",
      "Wire",
      "Gang of Four",
      "The Fall",
      "Bauhaus",
      "Siouxsie and the Banshees",
      "Magazine",
      "Public Image Ltd",
      "The Cure",
      "Echo & the Bunnymen",
      "The Chameleons",
      "The Sound",
      "Killing Joke",
      "Comsat Angels",
      "Danse Society",
      "Sad Lovers and Giants",
      "Tuxedomoon",
      "Clan of Xymox",
      "Virgin Prunes",
      "Specimen",
      "Theatre of Hate",
      "Sex Gang Children",
      "Alien Sex Fiend",
      "UK Decay",
      "Southern Death Cult",
      "Interpol",
      "Savages",
      "Preoccupations",
      "Ought",
      "Protomartyr",
    ],
  },
  {
    id: "new-wave",
    name: "New Wave",
    emoji: "🌊",
    group: "Punk",
    searchTerms: [
      "Talking Heads",
      "Devo",
      "Blondie",
      "Elvis Costello",
      "The Cars",
      "New Order",
      "Depeche Mode",
      "The Smiths",
      "Orchestral Manoeuvres in the Dark",
      "Human League",
      "Scritti Politti",
      "ABC",
      "Heaven 17",
      "Orange Juice",
      "Josef K",
      "Altered Images",
      "Cocteau Twins",
      "The Blue Nile",
      "Associates",
      "Prefab Sprout",
      "Ultravox",
      "Gary Numan",
      "Simple Minds",
      "Japan",
      "Duran Duran",
      "Spandau Ballet",
      "A Flock of Seagulls",
      "Howard Jones",
      "Haircut 100",
      "Yazoo",
    ],
  },
  // ── Reggae ────────────────────────────────────────────────────────────────
  {
    id: "reggae",
    name: "Reggae",
    emoji: "🌴",
    group: "Reggae",
    searchTerms: [
      "Bob Marley",
      "Peter Tosh",
      "Burning Spear",
      "Lee Scratch Perry",
      "Augustus Pablo",
      "King Tubby",
      "Horace Andy",
      "Gregory Isaacs",
      "Dennis Brown",
      "Culture",
      "The Abyssinians",
      "Steel Pulse",
      "Linton Kwesi Johnson",
      "Black Uhuru",
      "Junior Murvin",
      "Max Romeo",
      "The Congos",
      "Sizzla",
      "Luciano",
      "Capleton",
      "Toots and the Maytals",
      "Desmond Dekker",
      "Jimmy Cliff",
      "Ken Boothe",
      "Alton Ellis",
      "John Holt",
      "Delroy Wilson",
      "Eric Donaldson",
      "Slim Smith",
      "Freddie McGregor",
    ],
  },
  {
    id: "dub",
    name: "Dub",
    emoji: "🌫️",
    group: "Reggae",
    searchTerms: [
      "King Tubby",
      "Lee Scratch Perry",
      "Augustus Pablo",
      "Scientist",
      "Prince Jammy",
      "Yabby You",
      "Joe Gibbs",
      "Mikey Dread",
      "The Upsetters",
      "Channel One",
      "Bunny Lee",
      "Keith Hudson",
      "Vivian Jackson",
      "Lloyd Daley",
      "Niney the Observer",
      "Mad Professor",
      "Sly & Robbie",
      "Carlton Barrett",
      "Winston Edwards",
      // "Clive Chin", // no iTunes preview
      // "Errol Thompson", // no iTunes preview
      // "Jack Ruby", // no iTunes preview
      "Gussie Clarke",
      "Prince Far I",
      "Jah Shaka",
      "Adrian Sherwood",
      "On-U Sound",
      "Dennis Bovell",
      "Robbie Shakespeare",
      // "Style Scott", // no iTunes preview
    ],
  },
  // ── Ska ──────────────────────────────────────────────────────────────────
  {
    id: "ska",
    name: "Ska",
    emoji: "🎺",
    group: "Reggae",
    searchTerms: [
      "The Specials",
      "Madness",
      "The Selecter",
      "The Beat",
      "Skatalites",
      "Prince Buster",
      "Laurel Aitken",
      "Derrick Morgan",
      "Toots and the Maytals",
      "Desmond Dekker",
      "Jimmy Cliff",
      "Ken Boothe",
      "Alton Ellis",
      "Jackie Mittoo",
      "Ernest Ranglin",
      "Don Drummond",
      "Roland Alphonso",
      "Rico Rodriguez",
      "Byron Lee and the Dragonaires",
      "Justin Hinds",
      // "Eric Morris", // no iTunes preview
      // "Owen Gray", // no iTunes preview
      "Delroy Wilson",
      // "Stranger Cole", // no iTunes preview
      "Bad Manners",
      "English Beat",
      "Bodysnatchers",
      "Fishbone",
      "Reel Big Fish",
      "The Toasters",
    ],
  },
  // ── Classical ─────────────────────────────────────────────────────────────
  // {
  //   id: "classical",
  //   name: "Classical",
  //   emoji: "🎻",
  //   group: "Classical",
  //   searchTerms: [
  //     "Johann Sebastian Bach",
  //     "Ludwig van Beethoven",
  //     "Wolfgang Amadeus Mozart",
  //     "Franz Schubert",
  //     "Johannes Brahms",
  //     "Gustav Mahler",
  //     "Anton Bruckner",
  //     "Dmitri Shostakovich",
  //     "Béla Bartók",
  //     "Igor Stravinsky",
  //     "Claude Debussy",
  //     "Maurice Ravel",
  //     "Arnold Schoenberg",
  //     "Alban Berg",
  //     "Anton Webern",
  //     "Olivier Messiaen",
  //     "György Ligeti",
  //     "Arvo Pärt",
  //     "Morton Feldman",
  //     "Helmut Lachenmann",
  //     "Franz Joseph Haydn",
  //     "Robert Schumann",
  //     "Frédéric Chopin",
  //     "Franz Liszt",
  //     "Antonín Dvořák",
  //     "Jean Sibelius",
  //     "Sergei Prokofiev",
  //     "Sergei Rachmaninoff",
  //     "Paul Hindemith",
  //     "Karlheinz Stockhausen",
  //   ],
  // },
];

export const GENRE_THEMES: Record<string, GenreTheme> = {
  // Pop — neon pink / cyan / magenta ben distinti
  pop: {
    accent: "#ff2d78",
    accentGlow: "#ff2d7860",
    bg: "#120006",
    bgSurface: "#1e000f",
  },
  "brit-pop": {
    accent: "#ffe600",
    accentGlow: "#ffe60060",
    bg: "#0f0d00",
    bgSurface: "#1a1800",
  },
  kpop: {
    accent: "#ff00cc",
    accentGlow: "#ff00cc60",
    bg: "#130010",
    bgSurface: "#200018",
  },
  // Rock — rosso fuoco / arancio elettrico / verde acido / azzurro
  rock: {
    accent: "#ff3300",
    accentGlow: "#ff330060",
    bg: "#130200",
    bgSurface: "#1e0500",
  },
  "hard-rock": {
    accent: "#ff7700",
    accentGlow: "#ff770060",
    bg: "#110200",
    bgSurface: "#1c0400",
  },
  "stoner-rock": {
    accent: "#ccff00",
    accentGlow: "#ccff0060",
    bg: "#080c00",
    bgSurface: "#111500",
  },
  "post-rock": {
    accent: "#00cfff",
    accentGlow: "#00cfff60",
    bg: "#020c10",
    bgSurface: "#04141c",
  },
  alternative: {
    accent: "#ff44aa",
    accentGlow: "#ff44aa60",
    bg: "#120008",
    bgSurface: "#1e0012",
  },
  // Metal — argento brillante / rosso laser / porpora acceso / viola freddo
  metal: {
    accent: "#e8e8ff",
    accentGlow: "#e8e8ff50",
    bg: "#080808",
    bgSurface: "#111118",
  },
  "trash-metal": {
    accent: "#ff0022",
    accentGlow: "#ff002260",
    bg: "#100000",
    bgSurface: "#1a0000",
  },
  "death-metal": {
    accent: "#cc0000",
    accentGlow: "#cc000060",
    bg: "#0a0000",
    bgSurface: "#140000",
  },
  "black-metal": {
    accent: "#7755ff",
    accentGlow: "#7755ff50",
    bg: "#03030a",
    bgSurface: "#08081a",
  },
  // Hip-Hop — oro / arancio neon
  rap: {
    accent: "#ffd000",
    accentGlow: "#ffd00060",
    bg: "#0f0d00",
    bgSurface: "#1a1500",
  },
  hiphop: {
    accent: "#ff6600",
    accentGlow: "#ff660060",
    bg: "#0f0700",
    bgSurface: "#1a0e00",
  },
  // Electronic — verde acqua
  electronic: {
    accent: "#00ffe0",
    accentGlow: "#00ffe060",
    bg: "#00100d",
    bgSurface: "#001a15",
  },
  dub: {
    accent: "#aaff00",
    accentGlow: "#aaff0060",
    bg: "#0a1000",
    bgSurface: "#121a00",
  },
  // Jazz — ambra calda
  jazz: {
    accent: "#ffaa00",
    accentGlow: "#ffaa0060",
    bg: "#0d0900",
    bgSurface: "#1a1200",
  },
  // Soul
  rnb: {
    accent: "#cc44ff",
    accentGlow: "#cc44ff60",
    bg: "#0d0020",
    bgSurface: "#160030",
  },
  funk: {
    accent: "#ff8800",
    accentGlow: "#ff880060",
    bg: "#100600",
    bgSurface: "#1a0e00",
  },
  // Blues — blu elettrico
  blues: {
    accent: "#2266ff",
    accentGlow: "#2266ff60",
    bg: "#000820",
    bgSurface: "#000f30",
  },
  // Folk — terra/ocra distinti
  folk: {
    accent: "#dd9933",
    accentGlow: "#dd993360",
    bg: "#0d0800",
    bgSurface: "#181200",
  },
  country: {
    accent: "#ffcc44",
    accentGlow: "#ffcc4460",
    bg: "#0d0800",
    bgSurface: "#1a1200",
  },
  // Punk
  punk: {
    accent: "#ff0088",
    accentGlow: "#ff008860",
    bg: "#130010",
    bgSurface: "#1e0018",
  },
  "hardcore-punk": {
    accent: "#ff2200",
    accentGlow: "#ff220060",
    bg: "#100100",
    bgSurface: "#190200",
  },
  // Reggae
  reggae: {
    accent: "#00ee44",
    accentGlow: "#00ee4460",
    bg: "#020d02",
    bgSurface: "#041504",
  },
  ska: {
    accent: "#ffdd00",
    accentGlow: "#ffdd0060",
    bg: "#0d0c00",
    bgSurface: "#1a1800",
  },

  // Rock aggiuntivi
  grunge: {
    accent: "#8b7355",
    accentGlow: "#8b735560",
    bg: "#080604",
    bgSurface: "#110e08",
  },
  psychedelic: {
    accent: "#cc00ff",
    accentGlow: "#cc00ff60",
    bg: "#0d0015",
    bgSurface: "#160022",
  },
  "noise-rock": {
    accent: "#ff4400",
    accentGlow: "#ff440060",
    bg: "#130300",
    bgSurface: "#1e0500",
  },
  "indie-pop": {
    accent: "#ff99cc",
    accentGlow: "#ff99cc60",
    bg: "#12000a",
    bgSurface: "#1e0014",
  },
  // Punk aggiuntivi
  "post-hardcore": {
    accent: "#ff6600",
    accentGlow: "#ff660060",
    bg: "#100400",
    bgSurface: "#1a0800",
  },
  "post-punk": {
    accent: "#aaaaff",
    accentGlow: "#aaaaff50",
    bg: "#040408",
    bgSurface: "#080812",
  },
  "new-wave": {
    accent: "#00ccff",
    accentGlow: "#00ccff60",
    bg: "#00080d",
    bgSurface: "#001218",
  },
  emo: {
    accent: "#ff3366",
    accentGlow: "#ff336660",
    bg: "#120005",
    bgSurface: "#1c000b",
  },
  // Soul aggiuntivi
  disco: {
    accent: "#ffcc00",
    accentGlow: "#ffcc0060",
    bg: "#0d0a00",
    bgSurface: "#1a1500",
  },
  motown: {
    accent: "#ff6633",
    accentGlow: "#ff663360",
    bg: "#120400",
    bgSurface: "#1c0800",
  },
  gospel: {
    accent: "#ffaa33",
    accentGlow: "#ffaa3360",
    bg: "#0d0700",
    bgSurface: "#1a1000",
  },
  afrobeat: {
    accent: "#33ff99",
    accentGlow: "#33ff9960",
    bg: "#001a0a",
    bgSurface: "#002914",
  },
  latin: {
    accent: "#ff2200",
    accentGlow: "#ff220060",
    bg: "#130100",
    bgSurface: "#1f0200",
  },
  // Electronic aggiuntivo
  "idm-ambient": {
    accent: "#99aaff",
    accentGlow: "#99aaff50",
    bg: "#03040d",
    bgSurface: "#060818",
  },
  // Classical — bianco caldo
  classical: {
    accent: "#fff0cc",
    accentGlow: "#fff0cc40",
    bg: "#0d0c08",
    bgSurface: "#181610",
  },
};

export const DEFAULT_THEME: GenreTheme = {
  accent: "#e8ff47",
  accentGlow: "#e8ff4740",
  bg: "#0a0a0f",
  bgSurface: "#13131e",
};

// ─── Helper ───────────────────────────────────────────────────────────────────

export function getGenreById(id: string): Genre | undefined {
  return GENRES.find((g) => g.id === id);
}

export function getThemeForGenre(genreId: string | null): GenreTheme {
  if (!genreId) return DEFAULT_THEME;
  return GENRE_THEMES[genreId] ?? DEFAULT_THEME;
}

export function themeToCSSVars(theme: GenreTheme): React.CSSProperties {
  return {
    "--accent-primary": theme.accent,
    "--accent-glow": theme.accentGlow,
    "--bg-base": theme.bg,
    "--bg-surface": theme.bgSurface,
    "--bg-elevated": adjustBrightness(theme.bgSurface, 1.4),
  } as React.CSSProperties;
}

function adjustBrightness(hex: string, factor: number): string {
  const r = parseInt(hex.slice(1, 3), 16);
  const g = parseInt(hex.slice(3, 5), 16);
  const b = parseInt(hex.slice(5, 7), 16);
  const clamp = (v: number) => Math.min(255, Math.round(v * factor));
  return `rgb(${clamp(r)}, ${clamp(g)}, ${clamp(b)})`;
}
